
server.port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academy?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: ed
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace